### ISSUE TITLE
Donate Via Paypal Button is Broken

### ISSUE THREAD

**Issue by egelmex** [calaldees/barcampCanterbury#4]
I was going to do a shout out about getting on the supporters wall, but the link is broken.

**Comment by vext01** [comment]
Is this still an issue mex?

Works here:
![image](https://user-images.githubusercontent.com/604955/58702380-8a01f900-839d-11e9-9882-8d8c9d8c23d9.png)

**Comment by egelmex** [comment]
I get this on mobile

**Comment by vext01** [comment]
Mex, that last message didn't come through right, I don't think. So it doesn't work on mobile? Which browser?

Works on my android phone under firefox and duckduckgo browser.

**Comment by egelmex** [comment]
Under chrome on my one plus

**Comment by egelmex** [comment]
I just tried again and it worked...
