### ISSUE TITLE
Vegan Provision

### ISSUE THREAD

**Issue by calaldees** [calaldees/barcampCanterbury#7]
We need a plan

**Comment by vext01** [comment]
Why don't we ask any Vegans to make themselves known in the email we are sending later?

**Comment by calaldees** [comment]
We will ask Vegans to identify themselfs at the welcome desk
We will put in a separate order for supper at https://deliveroo.co.uk/menu/canterbury/canterbury/the-monument
Bit's for lunch should be purchased the day before. Something from M&S or Waitrose.
I will add these to the todo lists
